# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Saurabh Pradhan
tagline:          ''
description:      ' Researcher  @ <a href="http://uu.se" target="_blank"> Uppsala University</a> '
url:              https://srbhp.github.io
baseurl:          https://srbhp.github.io/

author:
  name:           'Saurabh Pradhan'
  url:            https://srbhp.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://srbhp.github.io
