# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Saurabh Pradhan
tagline:          ''
description:      ' Researcher  '
url:              https://srbhp.github.io
baseurl:          https://srbhp.github.io/

author:
  name:           'Saurabh Pradhan'
  url:            https://srbhp.github.io

paginate:         5



github:
  repo:           https://github.com/srbhp
